version: '3.8'

services:
  postgres:
    image: postgres:14.9
    container_name: postgres-jointestcase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: join
      POSTGRES_PASSWORD: joinpwd
      POSTGRES_DB: join
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-schema-install:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
